# Generated by Django 4.0.3 on 2023-07-06 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.TextField(max_length=100, unique=True, verbose_name='질문목록')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=50, verbose_name='투표항목')),
                ('votes', models.IntegerField(verbose_name='투표수')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category_name', to='polls.category', verbose_name='질문명')),
            ],
        ),
    ]
